version: "2"
services:
  app:
    image: jaggerwang.net/jw-tornado-demo:latest
    environment:
      DEBUG: 'false'
      PATH_APP: /app
      PATH_DATA: /data
      LOGGING_LOGGER_LEVEL: INFO
      TORNADO_SERVER_PORT: 8888
      TORNADO_SERVER_NUMPROCS: 0
      SESSION_COOKIE_SECRET: 385aH8CvtcP51v985E56OgQryoIpzr61
      SESSION_EXPIRES_SECONDS: 86400
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_NAME: jw_tornado_demo
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    ports:
    - 19900:8888
    volumes:
    - ~/data/jw-tornado-demo/app:/data
  mongodb:
    image: mongo:3
    volumes:
    - ~/data/jw-tornado-demo/mongodb:/data/db
  redis:
    image: redis:4
    command:
    - redis-server
    - --appendonly
    - 'yes'
    volumes:
    - ~/data/jw-tornado-demo/redis:/data
