version: "2"
services:
  server:
    environment:
      JWPY_ENV: development
      JWPY_DEBUG: "true"
      JWPY_LOGGING_HANDLER_LEVEL: DEBUG
      JWPY_LOGGING_LOGGER_LEVEL: DEBUG
    volumes:
      - ./:/app
      - ~/data/projects/jw-pyserver/server:/data
  mongodb:
    volumes:
      - ~/data/projects/jw-pyserver/mongodb:/data
  redis:
    volumes:
      - ~/data/projects/jw-pyserver/redis:/data
